import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  Future<void> generateReport(Map<String, dynamic> feedback) async {
    final doc = pw.Document();

    // Load fonts that support regular characters and emojis
    final font = await PdfGoogleFonts.openSansRegular();
    final boldFont = await PdfGoogleFonts.openSansBold();
    final emojiFont = await PdfGoogleFonts.notoColorEmoji();

    // Extract data from the feedback map
    final score = feedback['overall_score'] ?? 'N/A';
    final summary =
        feedback['overall_summary'] as String? ?? 'No summary provided.';
    final categories = feedback['feedback_categories'] as Map? ?? {};
    final improvements =
        (feedback['suggested_improvements'] as List?)?.cast<String>() ?? [];
    final answerFeedback = (feedback['answer_feedback'] as List?) ?? [];

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(
          base: font,
          bold: boldFont,
          fontFallback: [emojiFont],
        ),
        build: (pw.Context context) => [
          _buildHeader(context),
          pw.SizedBox(height: 20),
          _buildOverallScore(context, score),
          pw.SizedBox(height: 15),
          _buildSection(
            context,
            'Overall Summary',
            pw.Text(summary, style: const pw.TextStyle(lineSpacing: 2)),
          ),
          if (answerFeedback.isNotEmpty)
            _buildSection(
              context,
              'Answer Breakdown',
              _buildAnswerFeedback(answerFeedback),
            ),
          if (categories.isNotEmpty)
            _buildSection(
              context,
              'Feedback Categories',
              _buildCategories(categories),
            ),
          if (improvements.isNotEmpty)
            _buildSection(
              context,
              'Suggested Improvements',
              _buildImprovements(improvements),
            ),
        ],
      ),
    );

    // Use the 'printing' package to share or save the PDF
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => doc.save(),
    );
  }

  pw.Widget _buildHeader(pw.Context context) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Interview Performance Report',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 24),
        ),
        pw.SizedBox(height: 4),
        pw.Text('Generated by InterviewPrep AI'),
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 10),
          child: pw.Divider(thickness: 2),
        ),
      ],
    );
  }

  pw.Widget _buildOverallScore(pw.Context context, dynamic score) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Center(
        child: pw.Text(
          'Overall Score: $score / 10',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18),
        ),
      ),
    );
  }

  pw.Widget _buildSection(pw.Context context, String title, pw.Widget content) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(height: 20),
        pw.Text(
          title,
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16),
        ),
        pw.Divider(color: PdfColors.grey400, height: 1),
        pw.SizedBox(height: 8),
        content,
      ],
    );
  }

  pw.Widget _buildAnswerFeedback(List answerFeedback) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: answerFeedback.map((item) {
        final itemMap = item as Map<String, dynamic>;
        final q = itemMap['question'] ?? 'Unknown Question';
        final s = itemMap['answer_score'] ?? 'N/A';
        final f = itemMap['feedback'] ?? 'No feedback.';
        return pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 12),
          child: pw.Table(
            columnWidths: {
              0: const pw.IntrinsicColumnWidth(),
              1: const pw.FlexColumnWidth(),
            },
            children: [
              pw.TableRow(
                children: [
                  pw.Text(
                    'Q: ',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.Text(
                    '$q (Score: $s/10)',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                ],
              ),
              pw.TableRow(children: [pw.Text('A: '), pw.Text(f)]),
            ],
          ),
        );
      }).toList(),
    );
  }

  pw.Widget _buildCategories(Map categories) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: categories.entries.map((entry) {
        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 5),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                '${entry.key}: ',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Expanded(child: pw.Text(entry.value.toString())),
            ],
          ),
        );
      }).toList(),
    );
  }

  pw.Widget _buildImprovements(List<String> improvements) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: improvements.map((item) => pw.Text('• $item')).toList(),
    );
  }
}
