// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGUMssaZzoVEQ3w4GLjvyryAyD8T9k_V0',
    appId: '1:138105499785:web:b02a31fdb09a9263395658',
    messagingSenderId: '138105499785',
    projectId: 'grade-flow-bf692',
    authDomain: 'grade-flow-bf692.firebaseapp.com',
    storageBucket: 'grade-flow-bf692.firebasestorage.app',
    measurementId: 'G-P622SQCWL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf66tV0QoLQPIdG0ELKi-eSAVMxr33GQY',
    appId: '1:138105499785:android:3326f3704596f493395658',
    messagingSenderId: '138105499785',
    projectId: 'grade-flow-bf692',
    storageBucket: 'grade-flow-bf692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiRmdLXnzh7ZfzrzFXergECXJatqllII',
    appId: '1:138105499785:ios:a6300e1797c1c3ff395658',
    messagingSenderId: '138105499785',
    projectId: 'grade-flow-bf692',
    storageBucket: 'grade-flow-bf692.firebasestorage.app',
    iosBundleId: 'com.example.gradeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiRmdLXnzh7ZfzrzFXergECXJatqllII',
    appId: '1:138105499785:ios:a6300e1797c1c3ff395658',
    messagingSenderId: '138105499785',
    projectId: 'grade-flow-bf692',
    storageBucket: 'grade-flow-bf692.firebasestorage.app',
    iosBundleId: 'com.example.gradeflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGUMssaZzoVEQ3w4GLjvyryAyD8T9k_V0',
    appId: '1:138105499785:web:d1710ce75d6e75b0395658',
    messagingSenderId: '138105499785',
    projectId: 'grade-flow-bf692',
    authDomain: 'grade-flow-bf692.firebaseapp.com',
    storageBucket: 'grade-flow-bf692.firebasestorage.app',
    measurementId: 'G-27EKSWFXKR',
  );
}
